# Dolch Site Nouns. Must be something that can be "taken" or "given".
# Must be pluralized, or weird sentences might be constructed.

- "apples"
- "balls"
- "bears"
- "beds"
- "bells"
- "birds"
- "boats"
- "boxes"
- "cars"
- "cats"
- "chairs"
- "chickens"
- "coats"
- "cows"
- "dogs"
- "dolls"
- "ducks"
- "eggs"
- "fish"
- "flowers"
- "games"
- "horses"
- "kittens"
- "letters"
- "nests"
- "pigs"
- "rabbits"
- "rings"
- "seeds"
- "sheep"
- "shoes"
- "sticks"
- "tables"
- "toys"
- "trees"
- "watches"
