# Male Subjects
- subject: uncle
  pronouns: male
- subject: dad
  pronouns: male
- subject: brother
  pronouns: male
- subject: friend
  pronouns: male

# Female Subjects
- subject: aunt
  pronouns: female
- subject: mom
  pronouns: female
- subject: sister
  pronouns: female
- subject: friend
  pronouns: female
