# augend: The number being added to.
# addend: The number being added.
#
# augend + addend = sum

- "I have {{augend}} {{object}}. {{subject}} has {{addend}} {{object}}. How many {{object}} do we have all together?"
- "{{subject}} has {{addend}} {{object}}. I give {{subject_objective}} {{augend}} {{object}}. How many does {{subject_subjective}} have now?"
