# augend: The number being added to.
# addend: The number being added.
#
# augend + addend = sum

- "{{student}} has {{augend}} {{object}}. {{student_possessive}} {{subject}} has {{addend}} {{object}}. How many {{object}} do they have all together?"
- "{{student_possessive}} {{subject}} has {{addend}} {{object}}. {{student}} gives {{subject_objective}} {{augend}} {{object}}. How many does {{subject_subjective}} have now?"
