- "There are {{num_1}} {{parent_plural}}. There are {{num_2}} {{child_plural}} in each {{parent_singular}}. How many {{child_plural}} are there all together?"
- "I have {{num_1}} {{parent_plural}}. Each {{parent_singular}} has {{num_2}} {{child_plural}}. How many {{child_plural}} are there in total?"
