# minuend: The number subtracted from
# subtrahend: The number being subtracted
#
# minuend - subtrahend = difference

- "{{student_possessive}} {{subject}} has {{minuend}} {{object}}. If {{subject_subjective}} gives {{student}} {{subtrahend}} {{object}}, how many {{object}} does {{subject_subjective}} have left?"
- "{{student}} has {{minuend}} {{object}}. {{student_possessive}} {{subject}} takes {{subtrahend}} {{object}}. How many {{object}} does {{student}} have left?"
