# minuend: The number subtracted from
# subtrahend: The number being subtracted
#
# minuend - subtrahend = difference

- "{{subject}} has {{minuend}} {{object}}. If {{subject_subjective}} gives me {{subtrahend}} {{object}}, how many {{object}} does {{subject_subjective}} have left?"
- "I have {{minuend}} {{object}}. {{subject}} takes {{subtrahend}} {{object}}. How many {{object}} do I have left?"
