- "{{subject}} has {{num_2}} {{object}}. If {{subject_subjective}} gives me {{num_1}} {{object}}, how many {{object}} does {{subject_subjective}} have left?"
- "I have {{num_2}} {{object}}. {{subject}} takes {{num_1}} {{object}}. How many {{object}} do I have left?"
